- .github/workflows/build-test.yml
- packages/snap/snap.manifest.json
We should make sure the snap manifest is up to date as part of our CI process. Checking whether the working directory is clean is one way of doing that.
> Require clean working directory

- packages/site/src/components/Buttons.tsx
- packages/site/src/components/Card.tsx
- packages/site/src/components/Footer.tsx
- packages/site/src/components/Header.tsx
- packages/site/src/components/Home.tsx
- packages/site/src/components/Toggle.tsx
- packages/site/src/config/theme.ts
Use `rem` units instead of `px` on `font-size`, `padding` and `margin`.
Use [the 62.5% `font-size` trick](https://www.aleksandrhovhannisyan.com/blog/62-5-percent-font-size-trick) to facilitate use of `rem`. With this trick `1rem` = `10px`.
fixes: #2
> Use `rem` instead of `px`

- packages/site/src/components/Buttons.tsx
- packages/site/src/components/Header.tsx
- packages/site/src/components/Home.tsx
- packages/site/src/hooks/MetamaskContext.tsx
- packages/site/src/types/index.ts
- packages/site/src/types/snap.ts
- packages/site/src/utils/button.ts
- packages/site/src/utils/index.ts
- packages/site/src/utils/snap.ts
Always show a re-connect button if the utilized snap is a local snap.
Fixes partially: https://github.com/MetaMask/snaps-skunkworks/issues/763
> Show Reconnect button if the installed snap is a local snap

- package.json
- packages/snap/snap.manifest.json
- yarn.lock
This removes the use of `concurrently` in favour of `yarn workspaces foreach`.
Fixes a bug that would not let the `yarn start` command work if a workspace was renamed.
The `start:site` and `start:snap` are also deleted to avoid any errors if a workspace is renamed
> Use yarn workspaces instead of concurrently

- packages/site/src/components/Home.tsx
Hotfix for broken `wallet_getSnaps` in MetaMask Flask 10.20.0
> Hotfix: Always show and enable the `send hello` button.

- packages/site/src/components/Card.tsx
This makes it easy to use the card component for building forms, showing long form content, etc. This change made it easy to build the dapp for the Web3 Unleashed NFT Vault dapp.
> Make `Card` component more flexible

- packages/snap/package.json
- packages/snap/snap.manifest.json
- yarn.lock
Declares snap dependencies as non dev dependencies and bumps them to `0.32.2`
> Bump snaps dependencies to `0.32.2`

- .vscode/settings.json
Added VSCode settings file that enables linting `snap.manifest.json` files using our schema.
Preferably we would use `$schema` property in the JSON file itself, but that would make it fail superstruct validation in v1 release version. I've added a PR to fix that - https://github.com/MetaMask/snaps-monorepo/pull/1389, but it has to wait after we release feature freeze.
**This PR requires https://github.com/MetaMask/SIPs/pull/93 to be merged beforehand**
> Added JSON schema linting for manifest files

- packages/site/src/hooks/MetamaskContext.tsx
- packages/site/src/pages/index.tsx
- packages/site/src/types/custom.d.ts
- packages/site/src/utils/metamask.ts
- packages/site/src/utils/snap.ts
This allows the template dapp to detect if MetaMask has Snaps enabled.
It also finds the MetaMask provider if multiple are present. 
Also checks for flask if the Snap id is local.
> Add MetaMask Snaps feature detection

- packages/site/.env.production.dist
- packages/site/src/config/snap.ts
The documentation for how to set SNAP_ORIGIN in order to support local development and production versions was a little unclear, and the Accounts team misinterpreted it (see MetaMask/snap-simple-keyring#59)
In this PR, I have tried to make it a little clearer
> chore: improve SNAP_ORIGIN documentation

- packages/site/package.json
- yarn.lock
cross-env doesn't really do anything in Yarn 2 and above, so we might as well remove it
> chore: remove cross-env

- packages/snap/package.json
- yarn.lock
Bump `allow-scripts`. This removes a bunch of old dependencies and therefore also resolves some Dependabot alerts.
Also dedupes some recent dependency changes.
> Bump `allow-scripts`

- yarn.lock
The currently locked version of `@parcel/watcher`, `2.0.5`, doesn't contain arm64 builds for Linux. Among other things this prevents the site package from running properly in Docker on M1 macs. This fixes it.
> Update `@parcel/watcher` to `2.3.0`

- packages/snap/package.json
- packages/snap/snap.manifest.json
- packages/snap/src/index.test.ts
- packages/snap/src/index.ts
- yarn.lock
This replaces `@metamask/snaps-types` and `@metamask/snaps-ui` with `@metamask/snaps-sdk`.
> Use Snaps SDK

- packages/snap/package.json
Adds `mm-snap manifest` as a `prepublishOnly` script in the `/snaps` package to prevent publishing snaps with invalid manifests (especially invalid shasums).
> Add prepublishOnly script with Snap manifest validation

- packages/site/src/components/Header.tsx
- packages/site/src/hooks/MetamaskContext.tsx
- packages/site/src/pages/index.tsx
- packages/site/src/types/custom.d.ts
- packages/site/src/utils/metamask.ts
- packages/site/src/utils/snap.ts
Adds support for detecting provider via EIP-6963. This PR also refactors the provider logic across the app slightly to decouple from the `window.ethereum` global.
Closes #128
> Support EIP-6963

- packages/snap/package.json
- packages/snap/src/index.test.ts
- yarn.lock
This bumps `@metamask/snaps-jest` to `v7.0.0` in the template snap.
Fixes: #192
> Bump `@metamask/snaps-jest` to `7.0.0`

- packages/site/src/hooks/useInvokeSnap.ts
Fixes a problem where invoking the Snap would fail in Firefox.
> Fix `invokeSnap` in Firefox

- packages/snap/package.json
- yarn.lock
Declare this dependency explicitly, as it's currently necessary for the JSX components to work proplerly.
The same deps are already in the site package and get hoisted, which unintendedly makes everything work.
> Add React @types to Snap package

- packages/snap/package.json
- packages/snap/snap.manifest.json
- yarn.lock
Bump Snaps packages to latest bringing the template up to speed and giving devs the latest CLI and `snaps-jest` improvements.
> chore: Bump Snaps packages

- .github/workflows/build-lint-test.yml
- .github/workflows/main.yml
This replaces `actions/checkout` and `actions/setup-node` with `MetaMask/action-checkout-and-setup`.
> Implement `MetaMask/action-checkout-and-setup`

- .github/workflows/build-lint-test.yml
This replaces `actions/cache` with `actions/upload-artifact` and `actions/download-artifact`.
> Use `actions/upload-artifact` and `actions/download-artifact` instead of cache

- yarn.lock
Bump `msgpackr` to latest version, which is compatible with Node 23. 
Fixes https://github.com/MetaMask/template-snap-monorepo/issues/296
> chore: Bump msgpackr

- packages/site/package.json
- yarn.lock
This bumps Gatsby and related dependencies to the latest versions. This resolves some security issues in the dependencies.
> Bump `gatsby` and related dependencies

- yarn.lock
This bumps `es5-ext` to `0.10.64` to fix a security issue.
> Bump `es5-ext` to `0.10.64`

- package.json
- yarn.lock
This bumps `ws` from `8.11.0` to `8.17.1` to resolve [this Dependabot alert](https://github.com/MetaMask/template-snap-monorepo/security/dependabot/41). Unfortunately Gatsby is pinned to `8.11.0` so I had to add a resolution.
> Bump `ws` from `8.11.0` to `8.17.1`

- package.json
- yarn.lock
This bumps `cookie` from `0.5.0` to `0.7.1` to resolve [this Dependabot alert](https://github.com/MetaMask/template-snap-monorepo/security/dependabot/57). I bumped `socket.io` as well, since the latest version uses a fixed version of `cookie`. Unfortunately Gatsby is pinned to `0.5.0` so I had to add a resolution.
> Bump `cookie` from `0.5.0` to `0.7.1`
